"""add_comment_column_to_monthly_fees

Revision ID: a95bb177b5f1
Revises: 20260801_add_payment_and_fine_compat_columns
Create Date: 2026-08-27 11:17:18.585384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a95bb177b5f1'
down_revision: Union[str, None] = '20260801_add_payment_and_fine_compat_columns'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monthly_fees', sa.Column('comment', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monthly_fees', 'comment')
    # ### end Alembic commands ###
