"""add_treasury_adjustment_column

Revision ID: c9b9b2079b2e
Revises: a95bb177b5f1
Create Date: 2026-08-27 11:43:52.427590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9b9b2079b2e'
down_revision: Union[str, None] = 'a95bb177b5f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('club_settings', sa.Column('treasury_adjustment', sa.Numeric(precision=10, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('club_settings', 'treasury_adjustment')
    # ### end Alembic commands ###
